"""initial schema

Revision ID: 520a2618b6c1
Revises: 
Create Date: 2026-08-22 00:22:18.387522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '520a2618b6c1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('associated_type', sa.Enum('instruction_record', 'assessment', name='attachment_association_type'), nullable=False),
    sa.Column('associated_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_profiles',
    sa.Column('state_code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('last_verified', sa.Date(), nullable=False),
    sa.Column('source_urls', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('disclaimer', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('families',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('contact_info', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_requirements',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('required_subject', 'attendance_days', 'attendance_hours', 'testing', 'other', name='compliance_requirement_type'), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('numeric_value', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['compliance_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grade_scales',
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('weighted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('time_tracking_mode', sa.Enum('duration', 'start_end', 'disabled', name='time_tracking_mode'), nullable=False),
    sa.Column('curriculum_tracking_enabled', sa.Boolean(), nullable=False),
    sa.Column('active_compliance_profile_id', sa.Uuid(), nullable=True),
    sa.Column('report_branding_logo_path', sa.String(length=500), nullable=True),
    sa.Column('report_footer_text', sa.String(length=500), nullable=True),
    sa.Column('parent_educator_name', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['active_compliance_profile_id'], ['compliance_profiles.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_id')
    )
    op.create_table('students',
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('grade_level', sa.String(length=50), nullable=True),
    sa.Column('student_identifier', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grade_category_weights',
    sa.Column('grade_scale_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('weight_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grade_scale_id'], ['grade_scales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grade_scale_bands',
    sa.Column('grade_scale_id', sa.Uuid(), nullable=False),
    sa.Column('letter', sa.String(length=5), nullable=False),
    sa.Column('min_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grade_scale_id'], ['grade_scales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('school_years',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('track_instructional_days', sa.Boolean(), nullable=False),
    sa.Column('track_instructional_hours', sa.Boolean(), nullable=False),
    sa.Column('min_instructional_days', sa.Integer(), nullable=True),
    sa.Column('min_hours_per_day', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('compliance_profile_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['compliance_profile_id'], ['compliance_profiles.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subject_compliance_mappings',
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('compliance_requirement_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['compliance_requirement_id'], ['compliance_requirements.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('subject_id', 'compliance_requirement_id')
    )
    op.create_table('courses',
    sa.Column('school_year_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['school_year_id'], ['school_years.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('school_days',
    sa.Column('school_year_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('instructional', 'partial', 'non_instructional', 'holiday', 'vacation', 'sick', 'field_trip', 'other', name='school_day_status'), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['school_year_id'], ['school_years.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_year_id', 'date', name='uq_school_day_year_date')
    )
    op.create_table('curricula',
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('publisher', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lessons',
    sa.Column('curriculum_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('expected_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('completion_status', sa.Enum('not_started', 'in_progress', 'complete', name='lesson_status'), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curricula.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessments',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=True),
    sa.Column('curriculum_id', sa.Uuid(), nullable=True),
    sa.Column('lesson_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.Enum('assignment', 'quiz', 'test', 'project', 'oral', 'other', name='assessment_type'), nullable=False),
    sa.Column('points_earned', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('points_possible', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curricula.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instruction_records',
    sa.Column('school_day_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=True),
    sa.Column('curriculum_id', sa.Uuid(), nullable=True),
    sa.Column('lesson_id', sa.Uuid(), nullable=True),
    sa.Column('activity_description', sa.String(length=1000), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curricula.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['school_day_id'], ['school_days.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instruction_records')
    op.drop_table('assessments')
    op.drop_table('lessons')
    op.drop_table('curricula')
    op.drop_table('school_days')
    op.drop_table('courses')
    op.drop_table('subject_compliance_mappings')
    op.drop_table('school_years')
    op.drop_table('grade_scale_bands')
    op.drop_table('grade_category_weights')
    op.drop_table('subjects')
    op.drop_table('students')
    op.drop_table('settings')
    op.drop_table('grade_scales')
    op.drop_table('compliance_requirements')
    op.drop_table('families')
    op.drop_table('compliance_profiles')
    op.drop_table('attachments')
    # ### end Alembic commands ###
