"""add active_grade_scale to settings

Revision ID: 8644845c3bc2
Revises: 520a2618b6c1
Create Date: 2026-08-22 04:39:01.063715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8644845c3bc2'
down_revision: Union[str, None] = '520a2618b6c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('active_grade_scale_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'settings', 'grade_scales', ['active_grade_scale_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'settings', type_='foreignkey')
    op.drop_column('settings', 'active_grade_scale_id')
    # ### end Alembic commands ###
