"""drop unused settings.active_compliance_profile_id

Revision ID: ddec205db818
Revises: 8644845c3bc2
Create Date: 2026-08-22 08:19:52.354817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ddec205db818'
down_revision: Union[str, None] = '8644845c3bc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('settings_active_compliance_profile_id_fkey'), 'settings', type_='foreignkey')
    op.drop_column('settings', 'active_compliance_profile_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('active_compliance_profile_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('settings_active_compliance_profile_id_fkey'), 'settings', 'compliance_profiles', ['active_compliance_profile_id'], ['id'])
    # ### end Alembic commands ###
